google_cloud_project       = "--test-twitfix"
google_cloud_region        = "europe-west1"
google_cloud_zone          = "europe-west1-b"
google_app_engine_location = "europe-west"
twitfix_config_file        = "template.json"
